name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7.14, 3.5.7, 3.6.7, 3.6.8, 3.7.1, 3.7.2]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install pyenv
      run: |
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    - name: Cache Python
      uses: actions/cache@v1
      with:
        path: ~/.pyenv/versions/${{ matrix.python-version }}/
        key: ${{ runner.os }}-python-${{ matrix.python-version }}
    - name: Install Python ${{ matrix.python-version }}
      run: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        pyenv install ${{ matrix.python-version }} --skip-existing
        pyenv global ${{ matrix.python-version }}
        python -m pip install --upgrade pip
    - name: Test with tox
      run: |
        python -m pip install tox
        python -m tox
