name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5, 3.6.7, 3.6.8, 3.7.1, 3.7.2]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      run: |
        python -m pip install pyenv
        pyenv install ${{ matrix.python-version }}
        pyenv global ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with tox
      run: |
        python -m pip install tox
        tox
